version: '3'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    networks:
    - dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminek107

  mongo-express:
    image: mongo-express
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminek107@mongo:27017/
    depends_on:
    - mongo
    networks:
    - dev

  app:
    build:
      context: .
    ports:
    - "8000:8000"
    environment:
      mongo_dsn: mongodb://admin:adminek107@mongo:27017
    depends_on:
    - mongo
    networks:
    - dev

networks:
  dev:
